"""Build the static task workbench from reusable tools and edited task guides."""
import html,json,re,shutil
from urllib.parse import urlencode
from pathlib import Path
from markdown_it import MarkdownIt
R=Path(__file__).resolve().parent.parent
D=R/'docs'
BASE='https://henu-wang.github.io/practical-ai-workbench/'
md=MarkdownIt('commonmark',{'html':False}).enable('table')
tasks=[
 {'slug':'merge-pdf','title':'Merge PDF files online, free','short':'Merge PDFs','category':'PDF','description':'Combine PDF files in your browser, arrange their order, and download one PDF. No file uploads or account needed.','accept':'.pdf','multiple':True,'run':'Merge PDFs','steps':['Choose two or more PDFs','Arrange the file order','Merge and download'],'limits':'Up to 10 PDFs and 40 MiB total. Encrypted files are unsupported. Digital signatures and editable forms are not preserved.','sample':'Two PDFs → one PDF with 3 pages.'},
 {'slug':'extract-pdf-pages','title':'Extract pages from a PDF online, free','short':'Extract PDF pages','category':'PDF','description':'Select PDF page numbers or ranges, keep the order you specify, and download a new PDF without uploading your file.','accept':'.pdf','multiple':False,'run':'Extract pages','steps':['Choose one PDF','Enter pages, such as 1,3-5','Extract and download'],'limits':'Up to 40 MiB. Encrypted files are unsupported. Page numbers start at 1. Duplicate page numbers appear once.','sample':'Two-page PDF → pages 2,1 in a new PDF.'},
 {'slug':'compress-image','title':'Compress an image online, free','short':'Compress an image','category':'Images','description':'Compress a PNG, JPEG or WebP image locally in your browser. Adjust quality and dimensions, preview the image, and compare actual file sizes.','accept':'image/png,image/jpeg,image/webp','multiple':False,'run':'Compress image','steps':['Choose an image','Set format, quality and size limits','Preview and download'],'limits':'PNG, JPEG or WebP inputs up to 25 MiB and 40 megapixels. Exact target bytes are not guaranteed. JPEG uses a white background for transparency. Metadata and animation are not preserved.','sample':'1200 × 800 PNG → smaller JPEG or WebP.'},
 {'slug':'resize-image','title':'Resize an image online without cropping','short':'Resize an image','category':'Images','description':'Resize an image to fit your chosen width and height, preserve its proportions, and download a JPEG or WebP. Files stay in your browser.','accept':'image/png,image/jpeg,image/webp','multiple':False,'run':'Resize image','steps':['Choose an image','Set maximum width and height','Preview the dimensions and download'],'limits':'Fits inside the dimensions you enter, without cropping or enlarging. PNG, JPEG and WebP inputs; JPEG or WebP output. Metadata and animation are not preserved.','sample':'1200 × 800 → 600 × 400 pixels.'},
 {'slug':'remove-duplicate-csv-rows','title':'Remove duplicate rows from a CSV online','short':'Remove CSV duplicates','category':'CSV','description':'Remove duplicate CSV rows by all columns or a chosen key. Keep the first or last record, preview the result, and download the cleaned CSV.','accept':'.csv,text/csv','multiple':False,'run':'Remove duplicates','steps':['Choose a CSV or paste text','Choose the duplicate rule','Check counts and download'],'limits':'UTF-8 CSV with a unique header per column, up to 10 MiB. Matching is exact unless you enable trimming or case folding. Pasted text takes priority over a file.','sample':'4 data rows → 3 rows after removing one exact duplicate.'},
 {'slug':'csv-to-json','title':'Convert CSV to a JSON array online','short':'CSV to JSON','category':'CSV','description':'Convert CSV rows into a JSON array of objects, with column headers as keys. Keep leading zeros and quoted text without uploading a file.','accept':'.csv,text/csv','multiple':False,'run':'Convert to JSON','steps':['Choose a CSV or paste text','Convert and inspect the preview','Download the full JSON array'],'limits':'UTF-8 CSV with unique, non-empty column headers, up to 10 MiB. All values remain strings. Header whitespace is trimmed. Preview shows up to 8 rows; download includes all rows.','sample':'4 CSV data rows → 4 JSON objects.'}]

def write(path,content):
 temp=path.with_name(path.name+".tmp")
 temp.write_text(content)
 temp.replace(path)

def e(x):return html.escape(str(x),quote=True)
def layout(title,desc,url,body,depth=0,scripts=False,structured=None):
 prefix='../'*depth if depth else './'
 extra=''
 if scripts:extra=f'<script defer src="{prefix}vendor/pdf-lib-1.17.1.min.js"></script><script defer src="{prefix}vendor/papaparse-5.5.3.min.js"></script><script defer src="{prefix}assets/core.js"></script><script defer src="{prefix}assets/app.js"></script>'
 if structured:extra+='<script type="application/ld+json">'+json.dumps(structured).replace('<','\\u003c')+'</script>'
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{e(title)} | TokRepo Workflows</title><meta name="description" content="{e(desc)}"><link rel="canonical" href="{e(url)}"><meta name="robots" content="index,follow"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{e(url)}"><link rel="stylesheet" href="{prefix}assets/style.css">{extra}</head><body><header><a class="brand" href="{prefix}"><span class="mark">↗</span> TokRepo <b>Workflows</b></a><nav><a href="{prefix}#workflows">Workflows</a><a href="https://github.com/henu-wang/practical-ai-workbench">GitHub ↗</a></nav></header><main>{body}</main><footer><span>Practical guides. Reusable assets on TokRepo.</span><a href="https://github.com/henu-wang/practical-ai-workbench/blob/main/LICENSE">MIT license</a><a href="{prefix}privacy/">File privacy</a><a href="https://tokrepo.com/en">More workflows on TokRepo ↗</a></footer></body></html>'''

cards=[]
# Legacy URLs are preserved; rebuilding their unrelated sources is explicit.
import sys
if '--legacy' in sys.argv:
 for task in tasks:
  slug=task['slug'];out=D/slug;out.mkdir(exist_ok=True)
  content=R/'content'/f'{slug}.md'
  if not content.is_file():raise ValueError('Missing edited task guide: '+slug)
  raw=content.read_text();assert not re.search(r'^# ',raw,re.M), 'Body must not duplicate page H1'
  fields=f'<label class="file-choice">Choose {"PDF files" if task["category"]=="PDF" else "an image" if task["category"]=="Images" else "a CSV file"}<input id="files" type="file" accept="{task["accept"]}" {"multiple" if task["multiple"] else ""}></label><ol id="file-list" class="file-list"></ol>'
  if slug=='extract-pdf-pages':fields+='<label>Pages to extract<input id="pages" value="1" placeholder="1,3-5" autocomplete="off"></label>'
  if task['category']=='Images':
   width,height=(600,400) if slug=='resize-image' else (1200,800)
   fields+=f'<div class="field-grid"><label>Maximum width (pixels)<input id="width" type="number" min="1" max="10000" value="{width}"></label><label>Maximum height (pixels)<input id="height" type="number" min="1" max="10000" value="{height}"></label><label>Output format<select id="format"><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option></select></label><label>Quality <output id="quality-value">75%</output><input id="quality" type="range" min="0.1" max="1" step="0.05" value="0.75"></label></div>'
  if task['category']=='CSV':fields+='<label>Or paste CSV text<textarea id="csv-text" rows="5" placeholder="name,email,note"></textarea></label>'
  if slug=='remove-duplicate-csv-rows':fields+='<div class="field-grid"><label>Key column (blank = all columns)<input id="key-column" placeholder="For example: email"></label><label>Record to keep<select id="keep"><option value="first">First occurrence</option><option value="last">Last occurrence</option></select></label></div><div class="checks"><label><input type="checkbox" id="trim"> Ignore surrounding whitespace when matching</label><label><input type="checkbox" id="ignore-case"> Ignore letter case when matching</label><label><input type="checkbox" id="formula-safe"> Protect spreadsheet formulas on CSV export (adds an apostrophe)</label></div>'
  tool=f'<section class="tool" data-tool="{slug}" aria-label="{e(task["short"])} tool"><ol class="steps">'+''.join(f'<li><span>{i+1}</span>{e(s)}</li>' for i,s in enumerate(task['steps']))+f'</ol>{fields}<div class="actions"><button id="run" class="primary" type="button">{e(task["run"])}</button><button id="try-sample" type="button">Try example files</button><button id="reset" class="quiet" type="button">Clear</button></div><p id="status" class="status" role="status" aria-live="polite">Your files are processed in this browser. This app does not upload them.</p><p class="limits">{e(task["limits"])}</p><section id="result" class="result" hidden><h2>Your result</h2><p id="result-summary"></p><div id="preview"></div><a id="download" class="download">Download result ↓</a></section></section>'
  body=f'<a class="back" href="../">← All tools</a><div class="page-title"><p class="eyebrow">{task["category"]} / FREE LOCAL TOOL</p><h1>{e(task["title"])}</h1><p class="lead">{e(task["description"])}</p></div>'+tool+f'<p class="example-note"><strong>Try it first:</strong> {e(task["sample"])}</p><article class="guide">'+md.render(raw)+'</article><section class="related"><h2>Other file tasks</h2>'+''.join(f'<a href="../{x["slug"]}/">{e(x["short"])} →</a>' for x in tasks if x['slug']!=slug)+'</section>'
  structured={'@context':'https://schema.org','@type':'WebApplication','name':task['short'],'url':BASE+slug+'/','applicationCategory':'UtilitiesApplication','operatingSystem':'Modern browser','offers':{'@type':'Offer','price':'0','priceCurrency':'USD'},'description':task['description']}
  write((out/'index.html'),layout(task['title'],task['description'],BASE+slug+'/',body,1,True,structured))
  cards.append(f'<a class="card" href="./{slug}/"><span class="eyebrow">{e(task["category"])}</span><h2>{e(task["short"])}</h2><p>{e(task["description"])}</p><span class="card-link">Open tool →</span></a>')
recipes=json.loads((R/'recipes.json').read_text())['recipes']
recipe_cards=[]
for recipe in recipes:
 slug=recipe['slug']; url=BASE+'workflows/'+slug+'/'
 raw=(R/'recipes'/f'{slug}.md').read_text()
 assert not re.search(r'^# ',raw,re.M), 'Body must not duplicate H1'
 assets=recipe['assets']
 def asset_url(asset):
  return asset['url']+'?'+urlencode({'utm_source':'github_pages','utm_medium':'referral','utm_campaign':'tokrepo_search','utm_content':slug})
 asset_cards=''.join(f'<a class="asset-card" href="{e(asset_url(a))}"><strong>{e(a["title"])}</strong><span>{e(a["role"])}</span><b>Get this asset on TokRepo ↗</b></a>' for a in assets)
 kit=f'<section class="asset-kit" id="assets"><h2>Your TokRepo asset kit</h2><p>Open the asset pages for source links, setup requirements, and reusable instructions. This guide shows how to combine them.</p><div class="asset-grid">{asset_cards}</div></section>'
 body=f'<a class="back" href="../../">← All workflows</a><div class="page-title"><p class="eyebrow">{e(recipe["category"])} / GUIDE &amp; TEMPLATE</p><h1>{e(recipe["title"])}</h1><p class="lead">{e(recipe["description"])}</p><a class="primary hero-link" href="{e(asset_url(assets[0]))}">Get {e(assets[0]["title"])} on TokRepo ↗</a></div>'+kit+'<article class="guide recipe-guide">'+md.render(raw)+'</article><section class="related"><h2>Use the workflow again</h2><p>Keep the corresponding TokRepo assets for your next document, recording, or data task.</p>'+''.join(f'<a href="{e(asset_url(a))}">{e(a["title"])} on TokRepo ↗</a>' for a in assets)+'</section><section class="related"><h2>Related workflows</h2>'+''.join(f'<a href="../{x["slug"]}/">{e(x["title"])} →</a>' for x in recipes if x['slug']!=slug)+'</section>'
 structured={'@context':'https://schema.org','@type':'Article','headline':recipe['title'],'description':recipe['description'],'url':url,'inLanguage':'en','author':{'@type':'Organization','name':'TokRepo Editorial'},'datePublished':recipe['published_on'],'dateModified':recipe['updated_on']}
 out=D/'workflows'/slug;out.mkdir(parents=True,exist_ok=True)
 write((out/'index.html'),layout(recipe['title'],recipe['description'],url,body,2,False,structured))
 recipe_cards.append(f'<a class="card" href="./workflows/{slug}/"><span class="eyebrow">{e(recipe["category"])}</span><h2>{e(recipe["title"])}</h2><p>{e(recipe["description"])}</p><span class="card-link">Get the workflow &amp; assets →</span></a>')
if (R/'templates').exists():shutil.copytree(R/'templates',D/'templates',dirs_exist_ok=True)
body='<section class="hero"><p class="eyebrow">TOKREPO WORKFLOWS / FREE GUIDES &amp; TEMPLATES</p><h1>Turn everyday tasks<br>into reusable workflows.</h1><p class="lead">Transcribe a recording. Write clear meeting minutes. Recover a PDF table. Start with a practical guide, then get the matching prompts, skills and tools on TokRepo.</p><div class="badges"><span>Useful examples</span><span>Clear setup &amp; limits</span><span>Open-source guides</span></div><a class="primary hero-link" href="#workflows">Choose your task ↓</a></section><section id="workflows" class="cards">'+''.join(recipe_cards)+'</section><section class="about"><h2>Use the right assets together.</h2><p>Each guide connects a real task to a small kit of TokRepo assets, explains what each contributes, and helps you check the result. Templates are free to download. Individual tools and AI services have their own setup, licensing and costs.</p><a href="https://github.com/henu-wang/practical-ai-workbench">Edit or contribute to these guides on GitHub →</a></section><details class="about"><summary>Existing browser file utilities</summary><p>These earlier utilities remain available.</p><div class="related">'+''.join(f'<a href="./{x["slug"]}/">{e(x["short"])} →</a>' for x in tasks)+'</div></details>'
write((D/'index.html'),layout('Practical AI workflows, guides and templates','Combine TokRepo prompts, skills and tools for audio transcription, meeting minutes, PDF tables, presentations, clean CSV files and study flashcards.',BASE,body))
privacy=D/'privacy';privacy.mkdir(exist_ok=True)
write((privacy/'index.html'),layout('How this workbench handles your files','File processing happens in your browser. Read exactly what the workbench downloads, processes, and stores.',BASE+'privacy/','<h1>How your files are handled</h1><p>The tools read files you choose and process them in browser memory. This app has no file-upload endpoint, analytics tracker, hosted model call, or account system. The processing libraries are served with the site, rather than loaded from third-party CDNs.</p><p>Opening a page downloads its HTML, JavaScript and styles from GitHub Pages. “Try example files” downloads public sample files from this site. Those normal page requests do not contain your selected file contents.</p><p>The result is a browser-generated download. The Clear button releases the app’s file references and download URL. It does not delete your original files or downloads, and it cannot promise secure erasure of browser memory. GitHub Pages may retain normal request logs under its own policies.</p><p>External links open the services they point to; those sites have their own policies. Review the source code if your workflow has stronger confidentiality requirements.</p><a href="../">Back to tools →</a>',1))
urls=[BASE]+[BASE+'workflows/'+x['slug']+'/' for x in recipes]+[BASE+x['slug']+'/' for x in tasks]+[BASE+'privacy/']
write((D/'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+e(url)+'</loc></url>' for url in urls)+'</urlset>')
write((D/'robots.txt'),'User-agent: *\nAllow: /\nSitemap: '+BASE+'sitemap.xml\n')
write((D/'.nojekyll'),'')
write((R/'tasks.json'),json.dumps({'site_url':BASE,'published_on':'2026-10-07','tasks':tasks},indent=2)+'\n')
print('Built',len(recipes),'asset workflows and preserved',len(tasks),'legacy tools.')
